# Generated by Django 5.0.4 on 2024-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('StandAlone Headset', 'StandAlone Headset'), ('PC', 'PC')], max_length=50, null=True)),
            ],
        ),
    ]
